/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GradientAnimation: typeof import('./src/components/GradientAnimation.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
  }
}
